<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'Tidak ada pengguna dengan nama pengguna ini yang ditemukan di sistem. Jika Anda ingin menambahkan pencekalan tanpa tautan ke nama pengguna tertentu, biarkan kotak nama pengguna kosong.',
'No user ID message'		=>	'Tidak ada pengguna yang terdaftar dengan ID ini.',
'User is admin message'		=>	'Pengguna %s adalah administrator utama dan tidak dapat diblokir. Jika Anda ingin memblokir manajer puncak, Anda harus menurunkannya terlebih dahulu.',
'User is mod message'		=>	'Pengguna %s adalah administrator forum dan tidak dapat diblokir. Jika Anda ingin memblokir moderator forum, Anda harus menurunkannya terlebih dahulu.',
'Must enter message'		=>	'Anda harus memasukkan nama pengguna, alamat IP dan (setidaknya) alamat email.',
'Cannot ban guest message'	=>	'Pengguna tamu tidak dapat diblokir.',
'Invalid IP message'		=>	'Anda telah memasukkan rentang IP / IP yang tidak valid.',
'Invalid e-mail message'	=>	'Alamat email (misalnya user@domain.com) atau bagian dari domain alamat email (seperti domain.com) yang Anda masukkan tidak valid.',
'Duplicate domain message'	=>	'Domain %s sudah diblokir.',
'Duplicate e-mail message'	=>	'Alamat email %s sudah diblokir.',
'Invalid date message'		=>	'Anda telah memasukkan tanggal kedaluwarsa yang tidak valid.',
'Invalid date reasons'		=>	'Formatnya harus TTTT-BB-HH dan tanggal minimal harus satu hari yang akan datang.',
'Ban added redirect'		=>	'Blokir ditambahkan. Mengalihkan…' ,
'Ban edited redirect'		=>	'Blokir diedit. Mengalihkan…',
'Ban removed redirect'		=>	'Blokir dihapus. Mengalihkan…',

'New ban head'				=>	'Perampasan baru',
'Add ban subhead'			=>	'Tambahkan perampasan',
'Username label'			=>	'Username',
'Username help'				=>	'Username untuk diblokir (tidak peka terhadap huruf besar dan kecil).',
'Username advanced help'	=>	'Username untuk diblokir (huruf besar dan kecil tidak sensitif). Halaman berikutnya memungkinkan Anda memasukkan IP dan email yang diinginkan. Jika Anda hanya ingin memblokir rentang IP / IP atau email, biarkan kosong.',

'Ban search head'			=>	'Cari diblokir',
'Ban search subhead'		=>	'Tulis teks untuk dicari',
'Ban search info'			=>	'Untuk mencari diblokir di database. Masukkan satu atau lebih taruhan untuk dicari. Karakter bintang <strong> * </strong> dapat diterima. Kosongkan semua kotak untuk menampilkan semua yang diblokir.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'Pesan',
'Expire after label'		=>	'Kedaluwarsa setelah',
'Expire before label'		=>	'Kedaluwarsa sebelumnya',
'Order by label'			=>	'dipesan oleh',
'Order by username'			=>	'Username',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Email',
'Order by expire'			=>	'Tanggal habis tempo',
'Ascending'					=>	'Naik',
'Descending'				=>	'Menurun',
'Submit search'				=>	'Cari',

'E-mail label'				=>	'Email',
'E-mail help'				=>	'Email atau domain email yang ingin Anda blokir (misalnya: someone@somewhere.com atau somewhere.com) Untuk informasi lebih lanjut, lihat "Izinkan alamat email yang diblokir" di izin.',
'IP label'					=>	'Alamat IP / rentang IP',
'IP help'					=>	'Alamat IP atau rentang IP yang ingin Anda blokir (misalnya: 150.11.110.1 atau 150.11.110). Pisahkan alamat dengan spasi. Jika IP yang dimasukkan sebelumnya adalah IP terakhir yang diketahui dari pengguna ini dalam database.',
'IP help link'				=>	'Klik %s untuk melihat statistik IP pengguna ini.',
'Ban advanced head'			=>	'Pengaturan perampasan lanjutan',
'Ban advanced subhead'		=>	'Gabungkan perampasan melalui IP dan email',
'Ban message label'			=>	'Pesan perampasan',
'Ban message help'			=>	'Sebuah pesan yang akan ditampilkan kepada pengguna yang diblokir ketika dia mengunjungi forum.',
'Message expiry subhead'	=>	'Pesan perampasan dan kedaluwarsa',
'Ban IP range info'			=>	'Anda harus sangat berhati-hati saat memblokir rentang IP karena mungkin kompatibel dengan beberapa pengguna dengan komponen IP yang sama.',
'Expire date label'			=>	'Tanggal habis tempo',
'Expire date help'			=>	'Tanggal larangan ini harus dihapus secara otomatis (format: yyyy-mm-dd). Biarkan kosong untuk menghapus secara manual.',

'Results head'				=>	'Hasil Pencarian',
'Results username head'		=>	'Username',
'Results e-mail head'		=>	'Email',
'Results IP address head'	=>	'IP / Rentang-IP',
'Results expire head'		=>	'Tanggal habis tempo',
'Results message head'		=>	'Pesan',
'Results banned by head'	=>	'Diblokir oleh',
'Results actions head'		=>	'operasi',
'No match'					=>	'tidak cocok',
'Unknown'					=>	'Tidak diketahui',

);