<?php

// Language definitions used in install.php, localized by adaur

$lang_install = array(

'Choose install language'		=>	'Pilih bahasa penginstalan skrip',
'Choose install language info'	=>	'Bahasa yang digunakan untuk memasang skrip ini. Anda dapat memilih bahasa default yang digunakan untuk forum dari opsi di bawah ini',
'Install language'				=>	'Bahasa instalasi',
'Change language'				=>	'Ganti BAHASA',
'Already installed'				=>	'FluxBB tampaknya telah diinstal sebelumnya. Sebaiknya Anda membuka <a href="index.php"> di sini </a>.',
'You are running error'			=>	'Anda menjalankan %1 $s versi %2 $s. FluxBB %3 $s membutuhkan setidaknya %1 $s %4 $s untuk berjalan dengan benar. Anda harus memperbarui instalasi Anda %1 $s sebelum Anda dapat melanjutkan.',
'My FluxBB Forum'				=>	'Forum FluxBB saya',
'Description'					=>	'Sayangnya, tidak ada yang bisa mengatakan apa itu FluxBB. Anda harus mencobanya sendiri.',
'Username 1'					=>	'Nama pengguna minimal harus 2 karakter.',
'Username 2'					=>	'Nama pengguna tidak boleh lebih dari 25 karakter.',
'Username 3'					=>	'Nama guest telah dipesan.',
'Username 4'					=>	'Nama pengguna tidak boleh seperti alamat IP.',
'Username 5'					=>	'نام کاربری نمیتواند شامل همه کاراکترهای  \', "و ] یا  [ همزمان باشد.',
'Username 6'					=>	'نام کاربری نمیتواند شامل متن با فرمت تگ (BBCode) که در انجمن استفاده میشود باشد.',
'Short password'				=>	'کلمه عبور باید حداقل 6 کاراکتر باشد.',
'Passwords not match'			=>	'کلمه عبور با هم مطابقت ندارد.',
'Wrong email'					=>	'آدرس ایمیل مدیر که وارد کرده اید معتبر نمیباشد.',
'No board title'				=>	'شما باید عنوان انجمن را وارد کنید.',
'Error default language'		=>	'بنظر میرسد زبان پیش‌فرض انتخاب شده وجود ندارد.',
'Error default style'			=>	'بنظر میرسد قالب پیش‌فرض انتخاب شده وجود ندارد.',
'No DB extensions'				=>	'این محیط PHP پشتیبانی از پایگاه داده ای را که FluxBB پشتیبانی میکند را ندارد. برای نصب FluxBB نیازمند است که PHP پایگاه داده MySQL ، PostgreSQL یا SQLite را پشتیبانی کند.',
'Administrator username'		=>	'نام کاربری مدیر',
'Administrator email'			=>	'ایمیل مدیر',
'Board title'					=>	'عنوان انجمن',
'Base URL'						=>	'آدرس ( بدون اسلش در انتها ) انجمن FluxBB شما . این باید صحیح باشد.',
'Required field'				=>	'کادر لازم در این فرم میباشد.',
'FluxBB Installation'			=>	'پروسه نصب و راه اندازی انجمن ساز FluxBB',
'Welcome'						=>	'شما میخواهید FluxBB را نصب کنید . برای اینکه FluxBB نصب شود ، شما باید فرم هایی که در پایین است را تکمیل کنید . درصورت روبرو شدن با هرگونه اشکال در نصب ، لطفاً به مستندات مراجعه کنید.',
'Install'						=>	'نصب و راه اندازی FluxBB  %s',
'Errors'						=>	'این خطاها باید تصحیح شوند:',
'Database setup'				=>	'نصب و راه اندازی پایگاه داده',
'Info 1'						=>	'تمام اطلاعاتی که ما برای ایجاد یک اتصال با پایگاه داده شما داریم.',
'Select database'				=>	'نوع پایگاه داده خود را انتخاب کنید',
'Info 2'						=>	'یک پایگاه داده را انتخاب کنید . ما SQLite ، MySQL و PostgreSQL را پشتیبانی میکنیم.',
'Database type'					=>	'نوع پایگاه داده',
'Required'						=>	'(الزامی)',
'Database hostname'				=>	'میزبان سرور پایگاه داده خود را وارد کنید',
'Info 3'						=>	'اگر <CODE>localhost</CODE> کار نکرد ، شما میتوانید این اطلاعات را از میزبان وبسایت خود دریافت کنید .',
'Database server hostname'		=>	'میزبان سرور پایگاه داده',
'Database enter name'			=>	'نام پایگاه داده خود را وارد کنید',
'Info 4'						=>	'نام پایگاه داده ای که شما میخواهید FluxBB را در آن نصب کنید.',
'Database name'					=>	'نام پایگاه داده',
'Database enter informations'	=>	'نام کاربری و کلمه عبور پایگاه داده خود را وارد کنید',
'Database username'				=>	'نام کاربری پایگاه داده',
'Info 5'						=>	'نام کاربری و کلمه عبور MySQL شما ( درصورت استفاده از SQLite این مرحله را نادیده بگیرید ).',
'Database password'				=>	'کلمه عبور پایگاه داده',
'Database enter prefix'			=>	'پیشوند جدول پایگاه داده را وارد کنید',
'Info 6'						=>	'اگر تمایل دارید چندین FluxBB را در یک پایگاه داده نصب کنید، این گزینه را تغییر دهید.',
'Table prefix'					=>	'پیشوند جدول',
'Administration setup'			=>	'نصب و راه اندازی مدیریت',
'Info 7'						=>	'اولین حساب کاربری انجمن خود را ایجاد کنید.',
'Info 8'						=>	'نام کاربری باید بین 2 الی 25 کاراکتر طول داشته باشد . کلمه عبور شما حداقل باید 6 کاراکتر باشد . به یاد داشته باشید که کلمه عبور ها به بزرگی و کوچکی حروف حساسند.',
'Password'						=>	'کلمه عبور',
'Confirm password'				=>	'تائید کلمه عبور',
'Board setup'					=>	'نصب و راه اندازی انجمن',
'Info 11'						=>	'تنظیمات انجمن شما. بعدا ً میتوانید این را تغییر دهید.',
'General information'			=>	'عنوان و توضیحات انجمن خود را وارد کنید.',
'Board description'				=>	'توضیحات انجمن (HTML را پشتیبانی میکند)',
'Appearance'					=>	'شکل ظاهری',
'Info 15'						=>	'این انجمن شما می‌باشد. زبان و قالب مورد نظر خود را انتخاب کنید.',
'Default language'				=>	'زبان پیش‌فرض',
'Default style'					=>	'قالب پیش‌فرض',
'Start install'					=>	'شروع نصب',
'DB type not valid'				=>	'\'%s\' یک نوع پایگاه داده معتبر نمیباشد',
'Table prefix error'			=>	'پیشوند جدول \'%s\' حاوی کاراکترهای غیرمجاز میباشد و یا اینکه بسیار طولانی است . پیشوند میتواند شامل حروف A تا Z ، همه اعداد و کاراکتر زیر خط _ باشد . به هرحال نمیتواند با عدد شروع شود . حداکثر طول 40 کاراکتر میباشد . لطفاً یک پیشوند دیگری را انتخاب کنید',
'Prefix reserved'				=>	'پیشوند جدول \'sqlite_\' برای استفاده توسط موتور SQLite رزرو شده است . لطفاً یک پیشوند دیگری را انتخاب کنید',
'Existing table error'			=>	'جدولی به نام \'%susers\' هم اکنون در پایگاه داده \'%s\' وجود دارد . این بدان معنی است که FluxBB درحال حاضر نصب میباشد و یا قطعه ای از نرم افزار دیگر نصب است و یک یا چند نام جدول که FluxBB به آن نیاز دارد را اشغال کرده است . اگر مایل هستید چند کپی از FluxBB را در یک پایگاه داده مشابه نصب کنید ، شما باید پیشوند جدول متفاوتی را انتخاب کنید',
'InnoDB off'					=>	'بنظر میرسد InnoDB فعال نیست . لطفاً لایه ای از پایگاه داده را انتخاب کنید که پشتیبانی InnoDB نداشته باشد ، و یا اینکه InnoDB را در سرور MySQL خود فعال کنید',
'Administrators'				=>	'Manajer puncak',
'Administrator'					=>	'Direktur Jenderal',
'Moderators'					=>	'Manajer Komunitas',
'Moderator'						=>	'Direktur Asosiasi',
'Guests'						=>	'Pengguna tamu',
'Guest'							=>	'pengguna tamu',
'Members'						=>	'Anggota Asosiasi',
'Announcement'					=>	'Tulis pengumuman Anda di sini.',
'Rules'							=>	'Tulis aturan Anda di sini',
'Maintenance message'			=>	'Asosiasi ditutup sementara untuk pemeliharaan. Silakan coba lagi dalam beberapa menit.',
'Test post'						=>	'Pengiriman Tes',
'Message'						=>	'Jika Anda melihat ini (yang menurut saya), penginstalan FluxBB tampaknya dilakukan dengan benar! Sekarang masuk dan pergi ke panel kontrol admin untuk mengkonfigurasi forum Anda.',
'Test category'					=>	'Set eksperimental',
'Test forum'					=>	'Asosiasi Eksperimental',
'This is just a test forum'		=>	'Ini hanyalah forum eksperimental',
'Alert cache'					=>	'<STRONG>پوشه کش در حال حاضر قابل نوشتن نیست !</STRONG> برای اینکه FluxBB بتواند بدرستی کار کند ، پوشه <EM>%s</EM> باید توسط PHP قابل نوشتن باشد. از chmod برای تنظیم مطلوب مجوزهای پوشه استفاده کنید. اگر در این مورد شک دارید ، chmod را به 0777 تغییر دهید.',
'Alert avatar'					=>	'<STRONG>پوشه آواتار در حال حاضر قابل نوشتن نیست !</STRONG> برای اینکه کاربران قادر باشند تصویر آواتار خود را آپلود کنند باید ببینید که پوشه <EM>%s</EM> توسط PHP قابل نوشتن باشد. شما بعد میتوانید انتخاب کنید تصاویر آواتار در پوشه دیگری ذخیره شود ( مدیریت/ گزینه ها را ببینید).  از chmod برای تنظیم مطلوب مجوزهای پوشه استفاده کنید. اگر در این مورد شک دارید ، chmod را به 0777 تغییر دهید',
'Alert upload'					=>	'<STRONG> آپلود فایل بنظر میرسد بر روی این سرور غیرمجاز است !</STRONG> اگر میخواهید کاربران قادر باشند تصاویر آواتار خود را آپلود کنند شما باید تنظیمات پیکربندی file_uploads در PHP را فعال کنید. مدیریت/ گزینه ها/ ویژگی ها.',
'FluxBB has been installed'		=>	'FluxBB نصب شد . برای پایان دادن به عملیات نصب لطفاً دستورالعمل زیر را دنبال کنید.',
'Final instructions'			=>	'دستورالعمل نهائی',
'Info 17'						=>	'برای نهائی کردن عملیات نصب ، شما باید بر روی دکمه پایین کلیک کرده تا فایلی به نام config.php را دانلود کنید. سپس باید این فایل را در شاخه ریشه FluxBB نصب شده خود آپلود کنید.',
'Info 18'						=>	'زمانی که فایل config.php را آپلود کردید ، FluxBB کاملا ً نصب و راه اندازی خواهد شد ! تا آن لحظه ، میتوانید به <a href="index.php"> صفحه اصلی انجمن </a> بروید.',
'Download config.php file'		=>	'دانلود فایل config.php',
'FluxBB fully installed'		=>	'FluxBB کاملا ً نصب و راه اندازی شد ! حالا میتوانید به <a href="index.php"> صفحه اصلی انجمن </a> بروید.',

);
