<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Masukkan alamat email yang valid',
'Email legend 2'			=>	'Masukkan dan konfirmasi alamat email yang valid',
'Localisation legend'		=>	'Setel opsi pelokalan Anda',
'Time zone'					=>	'Zona waktu',
'Time zone info'			=>	'Agar forum menampilkan waktu dengan benar, Anda harus memilih zona waktu lokal Anda dengan benar. Jika waktu musim panas memengaruhi waktu Anda, Anda harus memeriksa opsi yang disediakan untuk kemajuan waktu 1 jam.',
'DST'						=>	'Waktu musim panas efektif (kemajuan waktu 1 jam).',
'Time format'				=>	'Format waktu',
'Date format'				=>	'Format tanggal',
'Default'					=>	'Default',
'Language'					=>	'Bahasa',
'Email setting info'		=>	'Pilih apakah alamat email Anda dapat dilihat oleh pengguna lain dan apakah Anda ingin pengguna lain dapat mengirimi Anda email melalui forum (formulir email).',
'Email setting 1'			=>	'Lihat email Anda ke pengguna lain.',
'Email setting 2'			=>	'Tidak menampilkan alamat email tetapi izin untuk mengirim email melalui forum.',
'Email setting 3'			=>	'Jangan tampilkan alamat email dan jangan izinkan email dikirim melalui forum.',
'Privacy options legend'	=>	'Setel opsi privasi Anda',
'Confirm pass'				=>	'Setujui password',

'Username too short'		=>	'Nama pengguna minimal harus 2 karakter. Pilih nama pengguna lain (lebih tinggi).',
'Username too long'			=>	'Nama pengguna tidak boleh lebih dari 25 karakter. Pilih nama pengguna lain (lebih pendek).',
'Username guest'			=>	'Nama tamu telah dipesan. Silakan pilih nama pengguna lain.',
'Username IP'				=>	'Nama pengguna harus seperti alamat IP. Silakan pilih nama pengguna lain.',
'Username reserved chars'	=>	'Nama pengguna tidak boleh mengandung karakter [\ dan ','] atau. Pilih nama pengguna lain.',
'Username BBCode'			=>	'Nama pengguna tidak boleh menyertakan salah satu format tag BBCode yang digunakan oleh komunitas. Silakan pilih nama pengguna lain.',
'Banned username'			=>	'Nama pengguna yang Anda masukkan di forum ini diblokir. Silakan pilih nama pengguna lain.',
'Pass too short'			=>	'Kata sandi minimal harus terdiri dari 6 karakter. Pilih kata sandi lain (lebih tinggi).',
'Pass not match'			=>	'Sandi tidak cocok.',
'Banned email'				=>	'Alamat email yang Anda masukkan di forum ini diblokir. Pilih alamat email lain.',
'Dupe email'				=>	'Orang lain telah terdaftar dengan alamat email ini. Pilih alamat email lain.',
'Sig too long'				=>	'Teks tanda tangan tidak boleh lebih dari %1 $s karakter. Harap kurangi %2 $s karakter dari teks tanda tangan Anda.',
'Sig too many lines'		=>	'Tanda tangan bisa lebih dari %s baris.',
'Bad ICQ'					=>	'Anda telah memasukkan ICQ UIN yang tidak valid. Silakan kembali dan perbaiki.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Moscow, Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Yekaterinburg',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Novosibirsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Krasnoyarsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita, Irkutsk',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Vladivostok',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Magadan',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands, Kamchatka',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
